# Generated by Django 5.0.3 on 2026-07-30 11:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0002_alter_itemcategory_options_alter_subhead_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Example: 2026-27', max_length=9, unique=True, verbose_name='Financial Year')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text='Only one financial year can remain active.')),
                ('is_closed', models.BooleanField(default=False, help_text='Closed financial years cannot accept new transactions.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Year',
                'verbose_name_plural': 'Financial Years',
                'db_table': 'fin_financial_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FundEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('OPENING', 'Opening Balance'), ('ADDITIONAL_CREDIT', 'Additional Credit')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('source', models.CharField(help_text='Example: Government grant, higher formation allocation, CSD profit or monthly cutting.', max_length=250)),
                ('authority_number', models.CharField(blank=True, max_length=100, null=True)),
                ('authority_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_CFA', 'Pending CFA Approval'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned for Correction'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('cfa_remarks', models.TextField(blank=True, null=True)),
                ('cfa_acted_at', models.DateTimeField(blank=True, null=True)),
                ('cfa_acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_entries_cfa_acted', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_entries', to='finance.financialyear')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('sub_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_entries', to='masterdata.subhead')),
            ],
            options={
                'verbose_name': 'Fund Entry',
                'verbose_name_plural': 'Fund Entries',
                'db_table': 'fin_fund_entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('OPENING', 'Opening Balance'), ('CREDIT', 'Additional Credit'), ('EXPENDITURE', 'Actual Expenditure'), ('CREDIT_REVERSAL', 'Credit Reversal'), ('EXPENDITURE_REVERSAL', 'Expenditure Reversal'), ('ADJUSTMENT_CREDIT', 'Credit Adjustment'), ('ADJUSTMENT_DEBIT', 'Debit Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_type', models.CharField(blank=True, help_text='Example: FUND_ENTRY, PAYMENT or REVERSAL.', max_length=50, null=True)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_transactions', to='finance.financialyear')),
                ('fund_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transaction', to='finance.fundentry')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('sub_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_transactions', to='masterdata.subhead')),
            ],
            options={
                'verbose_name': 'Fund Transaction',
                'verbose_name_plural': 'Fund Transactions',
                'db_table': 'fin_fund_transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
