# Generated by Django 5.0.3 on 2026-08-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundentry',
            name='entry_number',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
    ]
