# Generated by Django 5.0.3 on 2026-08-04 20:24

import django.core.validators
import django.db.models.deletion
import documentation.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=250, verbose_name='Document Name')),
                ('reference_number', models.CharField(blank=True, max_length=120, null=True, verbose_name='Reference Number')),
                ('category', models.CharField(choices=[('GFR', 'GFR'), ('DPM', 'Defence Procurement Manual'), ('DFPDS', 'Delegation of Financial Powers'), ('GEM', 'GeM Guidelines'), ('MOD', 'MoD Instructions'), ('ARMY_HQ', 'Army HQ Letters'), ('COMMAND', 'Command Instructions'), ('PCDA_CDA', 'PCDA / CDA Circulars'), ('UNIT_SOP', 'Unit SOPs'), ('OTHER', 'Other Important Documents')], max_length=30)),
                ('issuing_authority', models.CharField(max_length=180, verbose_name='Issuing Authority')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('version_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Version / Amendment Number')),
                ('description', models.TextField(blank=True, null=True)),
                ('document_file', models.FileField(upload_to=documentation.models.reference_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('preview_pdf', models.FileField(blank=True, help_text='Optional PDF preview for DOC/DOCX files. PDF documents do not need a separate preview.', null=True, upload_to=documentation.models.reference_preview_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Display this document in Quick Access.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supersedes', models.ForeignKey(blank=True, help_text='Select the older document replaced by this document.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='documentation.referencedocument')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_documents_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reference Document',
                'verbose_name_plural': 'Reference Documents',
                'db_table': 'doc_reference_documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['category'], name='doc_referen_categor_967b6f_idx'), models.Index(fields=['status'], name='doc_referen_status_29e929_idx'), models.Index(fields=['issuing_authority'], name='doc_referen_issuing_8c461f_idx'), models.Index(fields=['uploaded_at'], name='doc_referen_uploade_a7400a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='referencedocument',
            constraint=models.UniqueConstraint(fields=('document_name', 'reference_number', 'version_number'), name='unique_reference_document_version'),
        ),
    ]
