# Generated by Django 5.0.3 on 2026-07-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Item Categories'},
        ),
        migrations.AlterModelOptions(
            name='subhead',
            options={'ordering': ['fund_head__name', 'name'], 'verbose_name_plural': 'Sub Heads'},
        ),
    ]
