# Generated by Django 5.0.3 on 2026-07-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HEAD_CLERK', 'Head Clerk'), ('ACCOUNTS_CLERK', 'Accounts Clerk'), ('ACCOUNTS_JCO', 'Accounts JCO'), ('ACCOUNTS_OFFICER', 'Accounts Officer'), ('CFA', 'Competent Financial Authority (CFA)'), ('ADMINISTRATOR', 'Administrator')], default='ACCOUNTS_CLERK', max_length=30),
        ),
    ]
