# Generated by Django 5.0.3 on 2026-07-19 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0002_alter_itemcategory_options_alter_subhead_options'),
        ('requirements_mgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('current_stage', models.CharField(choices=[('SURVEY', 'Survey'), ('BID_BOQ', 'Bid / BOQ'), ('NOTING', 'Noting'), ('APPROVAL', 'Approval'), ('EAS', 'EAS'), ('SANCTION', 'Sanction'), ('GEM_ORDER', 'GeM Order / Contract'), ('INSPECTION', 'Inspection'), ('CRAC', 'CRAC'), ('CRV', 'CRV'), ('PAYMENT_TRACKING', 'Payment Tracking'), ('CASE_CLOSED', 'Case Closed'), ('RETURNED', 'Returned for Correction')], default='SURVEY', max_length=20)),
                ('sanctioned_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('survey_notes', models.TextField(blank=True, null=True)),
                ('bid_boq_details', models.TextField(blank=True, null=True)),
                ('comparative_statement', models.TextField(blank=True, null=True)),
                ('noting_text', models.TextField(blank=True, null=True)),
                ('approval_decision', models.TextField(blank=True, null=True)),
                ('eas_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('sanction_order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('gem_order_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('inspection_notes', models.TextField(blank=True, null=True)),
                ('crac_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('crv_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fund_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_cases', to='masterdata.fundhead')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('requirement_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_case', to='requirements_mgmt.requirementitem')),
            ],
            options={
                'verbose_name': 'Procurement Case',
                'verbose_name_plural': 'Procurement Cases',
                'db_table': 'proc_procurement_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_stage', models.CharField(max_length=20)),
                ('to_stage', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('ADVANCE', 'Advanced'), ('RETURN', 'Returned')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_transitions', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='procurement.procurementcase')),
            ],
            options={
                'verbose_name': 'Case Stage History',
                'verbose_name_plural': 'Case Stage History',
                'db_table': 'proc_case_stage_history',
                'ordering': ['created_at'],
            },
        ),
    ]
