# Generated by Django 5.0.3 on 2026-07-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('requirements_mgmt', '0002_alter_requirementitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementcase',
            name='requirement_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_case', to='requirements_mgmt.requirement'),
        ),
    ]
