# Generated by Django 5.0.3 on 2026-07-27 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_procurementcase_requirement_item'),
        ('requirements_mgmt', '0003_delete_requirementitem_delete_requirementrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noting_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('au', models.CharField(max_length=50, verbose_name='A/U')),
                ('amount_allotted', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_released', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_expended', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_AO', 'Pending Account Officer'), ('AO_DENIED', 'Returned by Account Officer'), ('PENDING_CFA', 'Pending CFA'), ('CFA_DENIED', 'Returned by CFA'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('ao_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('ao_remarks', models.TextField(blank=True, null=True)),
                ('ao_acted_at', models.DateTimeField(blank=True, null=True)),
                ('cfa_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('cfa_remarks', models.TextField(blank=True, null=True)),
                ('cfa_acted_at', models.DateTimeField(blank=True, null=True)),
                ('ao_acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noting_sheets_ao_reviewed', to=settings.AUTH_USER_MODEL)),
                ('cfa_acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noting_sheets_cfa_reviewed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noting_sheets_created', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='noting_sheet', to='requirements_mgmt.requirement')),
            ],
            options={
                'verbose_name': 'Noting Sheet',
                'verbose_name_plural': 'Noting Sheets',
                'db_table': 'proc_noting_sheets',
                'ordering': ['-created_at'],
            },
        ),
    ]
