# Generated by Django 5.0.3 on 2026-07-29 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_notingsheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(max_length=100, verbose_name='File No')),
                ('eas_id', models.CharField(max_length=100, verbose_name='EAS ID')),
                ('dsc_goods', models.CharField(max_length=250, verbose_name='DSC (Description) of Goods')),
                ('name_supplier', models.CharField(max_length=250, verbose_name='Name of Supplier')),
                ('purpose_broad', models.CharField(max_length=250, verbose_name='Purpose - Broad')),
                ('designation_cfa', models.CharField(max_length=150, verbose_name='Designation of CFA')),
                ('qty_sanctioned', models.PositiveIntegerField(verbose_name='Qty Sanctioned')),
                ('amount_sanction', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount Sanction')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cost Per Unit')),
                ('other_charges', models.CharField(blank=True, max_length=250, null=True, verbose_name='Other Associated Charges (e.g. freight)')),
                ('total_amount_words', models.CharField(max_length=500, verbose_name='Total Amount (in words)')),
                ('availability_fund', models.CharField(max_length=250, verbose_name='Availability of Fund')),
                ('sub_details_heads', models.CharField(max_length=250, verbose_name='Sub Details / Heads')),
                ('reference_no', models.CharField(max_length=150, verbose_name='Reference No')),
                ('name_paying_agent', models.CharField(max_length=250, verbose_name='Name of Paying Agency')),
                ('date_time', models.DateField(verbose_name='Date')),
                ('station', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=150, verbose_name='Unit')),
                ('type_id', models.CharField(blank=True, default='', max_length=50)),
                ('status_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_AO', 'Pending Account Officer'), ('AO_DENIED', 'Returned by Account Officer'), ('PENDING_CFA', 'Pending CFA'), ('CFA_DENIED', 'Returned by CFA'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('ao_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('ao_remarks', models.TextField(blank=True, null=True)),
                ('ao_acted_at', models.DateTimeField(blank=True, null=True)),
                ('cfa_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('cfa_remarks', models.TextField(blank=True, null=True)),
                ('cfa_acted_at', models.DateTimeField(blank=True, null=True)),
                ('ao_acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eas_ao_reviewed', to=settings.AUTH_USER_MODEL)),
                ('cfa_acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eas_cfa_reviewed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eas_created', to=settings.AUTH_USER_MODEL)),
                ('noting_sheet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='eas', to='procurement.notingsheet')),
            ],
            options={
                'verbose_name': 'EAS',
                'verbose_name_plural': 'EAS',
                'db_table': 'proc_eas',
                'ordering': ['-created_at'],
            },
        ),
    ]
