# Generated by Django 5.0.3 on 2026-08-02 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_eas'),
    ]

    operations = [
        migrations.AddField(
            model_name='eas',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='eas_documents/contract/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='eas',
            name='invoice_document',
            field=models.FileField(blank=True, null=True, upload_to='eas_documents/invoice/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='eas',
            name='sanction_document',
            field=models.FileField(blank=True, null=True, upload_to='eas_documents/sanction/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
