# Generated by Django 5.0.3 on 2026-08-07 18:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_eas_contract_document_eas_invoice_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notingsheet',
            name='au',
        ),
        migrations.AddField(
            model_name='notingsheet',
            name='approval_recipient',
            field=models.CharField(blank=True, help_text='Free text, e.g. "CFA (CO)" — who this is being sent to.', max_length=100),
        ),
        migrations.AddField(
            model_name='notingsheet',
            name='branch',
            field=models.CharField(default='Acct Branch', max_length=100),
        ),
        migrations.AddField(
            model_name='notingsheet',
            name='dated',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notingsheet',
            name='file_no',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notingsheet',
            name='financial_year',
            field=models.CharField(default='', help_text='e.g. 2026-27', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notingsheet',
            name='paragraph_1',
            field=models.CharField(default='', max_length=200, verbose_name='Paragraph 1 (Purport / Subject)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notingsheet',
            name='paragraph_2',
            field=models.TextField(default='', max_length=500, verbose_name='Paragraph 2 (Requirement / Justification)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notingsheet',
            name='remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notingsheet',
            name='sheet_no',
            field=models.CharField(default='One of One', max_length=50),
        ),
        migrations.CreateModel(
            name='NotingSheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Item Description')),
                ('au', models.CharField(max_length=50, verbose_name='A/U')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('noting_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.notingsheet')),
            ],
            options={
                'db_table': 'proc_noting_sheet_items',
                'ordering': ['id'],
            },
        ),
    ]
