# Generated by Django 5.0.3 on 2026-08-07 20:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_remove_notingsheet_au_notingsheet_approval_recipient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConveningOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convening_order_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('requirement_id_text', models.CharField(editable=False, max_length=100)),
                ('financial_year', models.CharField(editable=False, max_length=20)),
                ('fund_head_text', models.CharField(blank=True, editable=False, max_length=250)),
                ('sub_head_text', models.CharField(blank=True, editable=False, max_length=250)),
                ('procurement_mode', models.CharField(blank=True, editable=False, max_length=50)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('subject_title', models.CharField(max_length=500)),
                ('committee_purpose', models.CharField(choices=[('INSPECTION', 'Inspection'), ('PURCHASE', 'Purchase'), ('BOO', 'BOO'), ('OTHER', 'Other')], max_length=20)),
                ('place_of_proceedings', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('completion_due_date', models.DateField()),
                ('applicable_authority_rule', models.CharField(max_length=250)),
                ('additional_members', models.JSONField(blank=True, default=list)),
                ('terms_of_reference', models.TextField()),
                ('special_instructions', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True, max_length=1000)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('version_number', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('convening_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convening_orders_authority', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convening_orders_created', to=settings.AUTH_USER_MODEL)),
                ('member_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convening_orders_member1', to=settings.AUTH_USER_MODEL)),
                ('member_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convening_orders_member2', to=settings.AUTH_USER_MODEL)),
                ('member_secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convening_orders_secretary', to=settings.AUTH_USER_MODEL)),
                ('presiding_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convening_orders_presiding', to=settings.AUTH_USER_MODEL)),
                ('procurement_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convening_orders', to='procurement.procurementcase')),
                ('report_submission_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convening_orders_report_to', to=settings.AUTH_USER_MODEL)),
                ('technical_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convening_orders_technical', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proc_convening_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConveningOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='convening_orders/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('convening_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='procurement.conveningorder')),
            ],
            options={
                'db_table': 'proc_convening_order_attachments',
                'ordering': ['id'],
            },
        ),
    ]
