# Generated by Django 5.0.3 on 2026-08-08 22:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_conveningorder_conveningorderattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conveningorder',
            name='additional_members',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='applicable_authority_rule',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='committee_purpose',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='completion_due_date',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='convening_authority',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='fund_head_text',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='member_secretary',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='place_of_proceedings',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='procurement_mode',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='report_submission_to',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='requirement_id_text',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='special_instructions',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='sub_head_text',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='subject_title',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='technical_representative',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='terms_of_reference',
        ),
        migrations.RemoveField(
            model_name='conveningorder',
            name='version_number',
        ),
        migrations.AddField(
            model_name='conveningorder',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date of Completion',),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conveningorder',
            name='description',
            field=models.TextField(default='', verbose_name='Convening Order Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conveningorder',
            name='two_ic_appointment',
            field=models.CharField(default='2IC', max_length=100),
        ),
        migrations.AddField(
            model_name='conveningorder',
            name='two_ic_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conveningorder',
            name='two_ic_rank',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conveningorder',
            name='member_1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='conveningorder',
            name='member_2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='conveningorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='conveningorder',
            name='presiding_officer',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='conveningorder',
            name='procurement_case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='convening_order', to='procurement.procurementcase'),
        ),
        migrations.DeleteModel(
            name='ConveningOrderAttachment',
        ),
    ]
