# Generated by Django 5.0.3 on 2026-08-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_conveningorder_conveningorderattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notingsheet',
            name='paragraph_1',
            field=models.CharField(max_length=500, verbose_name='Paragraph 1 (Purport / Subject)'),
        ),
        migrations.AlterField(
            model_name='notingsheet',
            name='paragraph_2',
            field=models.TextField(max_length=1000, verbose_name='Paragraph 2 (Requirement / Justification)'),
        ),
        migrations.AlterField(
            model_name='notingsheet',
            name='remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
