# Generated by Django 5.0.3 on 2026-08-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_alter_notingsheet_paragraph_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notingsheet',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notingsheet',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='notingsheet',
            name='sheet_no',
            field=models.CharField(max_length=50),
        ),
    ]
