# Generated by Django 5.0.3 on 2026-08-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_alter_notingsheet_branch_alter_notingsheet_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eas',
            name='major',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Major'),
        ),
        migrations.AddField(
            model_name='eas',
            name='minor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Minor'),
        ),
        migrations.AlterField(
            model_name='notingsheet',
            name='branch',
            field=models.CharField(default='Acct Branch', max_length=100),
        ),
        migrations.AlterField(
            model_name='notingsheet',
            name='remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notingsheet',
            name='sheet_no',
            field=models.CharField(default='One of One', max_length=50),
        ),
    ]
