# Generated by Django 5.0.3 on 2026-08-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_merge_20260809_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveningorder',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
