# Generated by Django 5.0.3 on 2026-07-26 11:25

import django.db.models.deletion
import requirements_mgmt.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_mgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requirementitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='requirementitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='requirementitem',
            name='fund_head',
        ),
        migrations.RemoveField(
            model_name='requirementitem',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='requirementitem',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='requirementitem',
            name='requirement_request',
        ),
        migrations.RemoveField(
            model_name='requirementrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='requirementrequest',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='requirementrequest',
            name='raised_by',
        ),
        migrations.RemoveField(
            model_name='requirementrequest',
            name='unit',
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('item_name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('quantity', models.PositiveIntegerField()),
                ('purpose', models.CharField(max_length=250)),
                ('estimated_cost', models.CharField(max_length=250)),
                ('demanded_by', models.CharField(help_text='Who this item is being demanded for', max_length=250)),
                ('fund_head', models.CharField(blank=True, max_length=150, null=True)),
                ('purchase_mode', models.CharField(choices=[('GEM', 'GeM'), ('LOCAL', 'Local')], max_length=10)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='requirement_attachments/%Y/%m/', validators=[requirements_mgmt.models.validate_attachment_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_AO', 'Pending Account Officer'), ('AO_DENIED', 'Returned by Account Officer'), ('PENDING_CFA', 'Pending CFA'), ('CFA_DENIED', 'Returned by CFA'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('ao_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('ao_remarks', models.TextField(blank=True, null=True)),
                ('ao_acted_at', models.DateTimeField(blank=True, null=True)),
                ('cfa_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('cfa_remarks', models.TextField(blank=True, null=True)),
                ('cfa_acted_at', models.DateTimeField(blank=True, null=True)),
                ('ao_acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements_ao_reviewed', to=settings.AUTH_USER_MODEL)),
                ('cfa_acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements_cfa_reviewed', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requirement',
                'verbose_name_plural': 'Requirements',
                'db_table': 'req_requirements',
                'ordering': ['-created_at'],
            },
        ),
    ]
