# Generated by Django 5.0.3 on 2026-07-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_procurementcase_requirement_item'),
        ('requirements_mgmt', '0002_alter_requirementitem_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequirementItem',
        ),
        migrations.DeleteModel(
            name='RequirementRequest',
        ),
    ]
