# Generated by Django 5.0.3 on 2026-08-02 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_alter_itemcategory_options_alter_subhead_options'),
        ('requirements_mgmt', '0003_delete_requirementitem_delete_requirementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='sub_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='masterdata.subhead'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='fund_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='masterdata.fundhead'),
        ),
    ]
