# Generated by Django 5.0.3 on 2026-08-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_mgmt', '0004_requirement_sub_head_alter_requirement_fund_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='cost_per_unit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
